# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paperschedule.ui'
#
# Created: Mon Jul 20 20:55:38 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PaperScheduleDialog(object):
    def setupUi(self, PaperScheduleDialog):
        PaperScheduleDialog.setObjectName(_fromUtf8("PaperScheduleDialog"))
        PaperScheduleDialog.resize(636, 309)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PaperScheduleDialog.sizePolicy().hasHeightForWidth())
        PaperScheduleDialog.setSizePolicy(sizePolicy)
        self.paperInputButtonBox = QtGui.QDialogButtonBox(PaperScheduleDialog)
        self.paperInputButtonBox.setGeometry(QtCore.QRect(230, 230, 161, 32))
        self.paperInputButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.paperInputButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.paperInputButtonBox.setObjectName(_fromUtf8("paperInputButtonBox"))
        self.paperLength = QtGui.QLabel(PaperScheduleDialog)
        self.paperLength.setGeometry(QtCore.QRect(170, 130, 51, 31))
        self.paperLength.setObjectName(_fromUtf8("paperLength"))
        self.paperWeightEdit = QtGui.QLineEdit(PaperScheduleDialog)
        self.paperWeightEdit.setGeometry(QtCore.QRect(80, 132, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperWeightEdit.sizePolicy().hasHeightForWidth())
        self.paperWeightEdit.setSizePolicy(sizePolicy)
        self.paperWeightEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.paperWeightEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperWeightEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.paperWeightEdit.setInputMask(_fromUtf8(""))
        self.paperWeightEdit.setText(_fromUtf8(""))
        self.paperWeightEdit.setMaxLength(32767)
        self.paperWeightEdit.setCursorPosition(0)
        self.paperWeightEdit.setDragEnabled(False)
        self.paperWeightEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperWeightEdit.setProperty("clearButtonEnabled", False)
        self.paperWeightEdit.setObjectName(_fromUtf8("paperWeightEdit"))
        self.paperRollNumber = QtGui.QLabel(PaperScheduleDialog)
        self.paperRollNumber.setGeometry(QtCore.QRect(170, 90, 31, 41))
        self.paperRollNumber.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperRollNumber.setObjectName(_fromUtf8("paperRollNumber"))
        self.paperLengthEdit = QtGui.QLineEdit(PaperScheduleDialog)
        self.paperLengthEdit.setGeometry(QtCore.QRect(230, 130, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperLengthEdit.sizePolicy().hasHeightForWidth())
        self.paperLengthEdit.setSizePolicy(sizePolicy)
        self.paperLengthEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.paperLengthEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperLengthEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.paperLengthEdit.setInputMask(_fromUtf8(""))
        self.paperLengthEdit.setText(_fromUtf8(""))
        self.paperLengthEdit.setMaxLength(32767)
        self.paperLengthEdit.setCursorPosition(0)
        self.paperLengthEdit.setDragEnabled(False)
        self.paperLengthEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperLengthEdit.setProperty("clearButtonEnabled", False)
        self.paperLengthEdit.setObjectName(_fromUtf8("paperLengthEdit"))
        self.paperScheduleTitle = QtGui.QLabel(PaperScheduleDialog)
        self.paperScheduleTitle.setGeometry(QtCore.QRect(10, 12, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.paperScheduleTitle.setFont(font)
        self.paperScheduleTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperScheduleTitle.setObjectName(_fromUtf8("paperScheduleTitle"))
        self.paperWeight = QtGui.QLabel(PaperScheduleDialog)
        self.paperWeight.setGeometry(QtCore.QRect(10, 132, 51, 31))
        self.paperWeight.setObjectName(_fromUtf8("paperWeight"))
        self.paperWidthEdit = QtGui.QLineEdit(PaperScheduleDialog)
        self.paperWidthEdit.setGeometry(QtCore.QRect(80, 102, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperWidthEdit.sizePolicy().hasHeightForWidth())
        self.paperWidthEdit.setSizePolicy(sizePolicy)
        self.paperWidthEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.paperWidthEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperWidthEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.paperWidthEdit.setInputMask(_fromUtf8(""))
        self.paperWidthEdit.setText(_fromUtf8(""))
        self.paperWidthEdit.setMaxLength(32767)
        self.paperWidthEdit.setCursorPosition(0)
        self.paperWidthEdit.setDragEnabled(False)
        self.paperWidthEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperWidthEdit.setProperty("clearButtonEnabled", False)
        self.paperWidthEdit.setObjectName(_fromUtf8("paperWidthEdit"))
        self.paperRollNumberEdit = QtGui.QLineEdit(PaperScheduleDialog)
        self.paperRollNumberEdit.setGeometry(QtCore.QRect(230, 102, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperRollNumberEdit.sizePolicy().hasHeightForWidth())
        self.paperRollNumberEdit.setSizePolicy(sizePolicy)
        self.paperRollNumberEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.paperRollNumberEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperRollNumberEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.paperRollNumberEdit.setInputMask(_fromUtf8(""))
        self.paperRollNumberEdit.setText(_fromUtf8(""))
        self.paperRollNumberEdit.setMaxLength(32767)
        self.paperRollNumberEdit.setCursorPosition(0)
        self.paperRollNumberEdit.setDragEnabled(False)
        self.paperRollNumberEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperRollNumberEdit.setProperty("clearButtonEnabled", False)
        self.paperRollNumberEdit.setObjectName(_fromUtf8("paperRollNumberEdit"))
        self.paperWidth = QtGui.QLabel(PaperScheduleDialog)
        self.paperWidth.setGeometry(QtCore.QRect(10, 90, 61, 41))
        self.paperWidth.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperWidth.setObjectName(_fromUtf8("paperWidth"))
        self.paperScheduleNotice = QtGui.QLabel(PaperScheduleDialog)
        self.paperScheduleNotice.setGeometry(QtCore.QRect(10, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.paperScheduleNotice.setFont(font)
        self.paperScheduleNotice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperScheduleNotice.setObjectName(_fromUtf8("paperScheduleNotice"))
        self.paperLength_2 = QtGui.QLabel(PaperScheduleDialog)
        self.paperLength_2.setGeometry(QtCore.QRect(470, 130, 51, 31))
        self.paperLength_2.setObjectName(_fromUtf8("paperLength_2"))
        self.paperWidth_2 = QtGui.QLabel(PaperScheduleDialog)
        self.paperWidth_2.setGeometry(QtCore.QRect(310, 90, 61, 41))
        self.paperWidth_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperWidth_2.setObjectName(_fromUtf8("paperWidth_2"))
        self.paperRollNumberEdit_2 = QtGui.QLineEdit(PaperScheduleDialog)
        self.paperRollNumberEdit_2.setGeometry(QtCore.QRect(530, 102, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperRollNumberEdit_2.sizePolicy().hasHeightForWidth())
        self.paperRollNumberEdit_2.setSizePolicy(sizePolicy)
        self.paperRollNumberEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.paperRollNumberEdit_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperRollNumberEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.paperRollNumberEdit_2.setInputMask(_fromUtf8(""))
        self.paperRollNumberEdit_2.setText(_fromUtf8(""))
        self.paperRollNumberEdit_2.setMaxLength(32767)
        self.paperRollNumberEdit_2.setCursorPosition(0)
        self.paperRollNumberEdit_2.setDragEnabled(False)
        self.paperRollNumberEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperRollNumberEdit_2.setProperty("clearButtonEnabled", False)
        self.paperRollNumberEdit_2.setObjectName(_fromUtf8("paperRollNumberEdit_2"))
        self.paperWeight_2 = QtGui.QLabel(PaperScheduleDialog)
        self.paperWeight_2.setGeometry(QtCore.QRect(310, 132, 51, 31))
        self.paperWeight_2.setObjectName(_fromUtf8("paperWeight_2"))
        self.paperWeightEdit_2 = QtGui.QLineEdit(PaperScheduleDialog)
        self.paperWeightEdit_2.setGeometry(QtCore.QRect(380, 132, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperWeightEdit_2.sizePolicy().hasHeightForWidth())
        self.paperWeightEdit_2.setSizePolicy(sizePolicy)
        self.paperWeightEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.paperWeightEdit_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperWeightEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.paperWeightEdit_2.setInputMask(_fromUtf8(""))
        self.paperWeightEdit_2.setText(_fromUtf8(""))
        self.paperWeightEdit_2.setMaxLength(32767)
        self.paperWeightEdit_2.setCursorPosition(0)
        self.paperWeightEdit_2.setDragEnabled(False)
        self.paperWeightEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperWeightEdit_2.setProperty("clearButtonEnabled", False)
        self.paperWeightEdit_2.setObjectName(_fromUtf8("paperWeightEdit_2"))
        self.paperLengthEdit_2 = QtGui.QLineEdit(PaperScheduleDialog)
        self.paperLengthEdit_2.setGeometry(QtCore.QRect(530, 130, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperLengthEdit_2.sizePolicy().hasHeightForWidth())
        self.paperLengthEdit_2.setSizePolicy(sizePolicy)
        self.paperLengthEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.paperLengthEdit_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperLengthEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.paperLengthEdit_2.setInputMask(_fromUtf8(""))
        self.paperLengthEdit_2.setText(_fromUtf8(""))
        self.paperLengthEdit_2.setMaxLength(32767)
        self.paperLengthEdit_2.setCursorPosition(0)
        self.paperLengthEdit_2.setDragEnabled(False)
        self.paperLengthEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperLengthEdit_2.setProperty("clearButtonEnabled", False)
        self.paperLengthEdit_2.setObjectName(_fromUtf8("paperLengthEdit_2"))
        self.paperRollNumber_2 = QtGui.QLabel(PaperScheduleDialog)
        self.paperRollNumber_2.setGeometry(QtCore.QRect(470, 90, 31, 41))
        self.paperRollNumber_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperRollNumber_2.setObjectName(_fromUtf8("paperRollNumber_2"))
        self.paperWidthEdit_2 = QtGui.QLineEdit(PaperScheduleDialog)
        self.paperWidthEdit_2.setGeometry(QtCore.QRect(380, 102, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperWidthEdit_2.sizePolicy().hasHeightForWidth())
        self.paperWidthEdit_2.setSizePolicy(sizePolicy)
        self.paperWidthEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.paperWidthEdit_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperWidthEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.paperWidthEdit_2.setInputMask(_fromUtf8(""))
        self.paperWidthEdit_2.setText(_fromUtf8(""))
        self.paperWidthEdit_2.setMaxLength(32767)
        self.paperWidthEdit_2.setCursorPosition(0)
        self.paperWidthEdit_2.setDragEnabled(False)
        self.paperWidthEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperWidthEdit_2.setProperty("clearButtonEnabled", False)
        self.paperWidthEdit_2.setObjectName(_fromUtf8("paperWidthEdit_2"))
        self.paperScheduleNotice_2 = QtGui.QLabel(PaperScheduleDialog)
        self.paperScheduleNotice_2.setGeometry(QtCore.QRect(310, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.paperScheduleNotice_2.setFont(font)
        self.paperScheduleNotice_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperScheduleNotice_2.setObjectName(_fromUtf8("paperScheduleNotice_2"))

        self.retranslateUi(PaperScheduleDialog)
        QtCore.QObject.connect(self.paperInputButtonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PaperScheduleDialog.accept)
        QtCore.QObject.connect(self.paperInputButtonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PaperScheduleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PaperScheduleDialog)

    def retranslateUi(self, PaperScheduleDialog):
        PaperScheduleDialog.setWindowTitle(_translate("PaperScheduleDialog", "正規紙排單", None))
        self.paperLength.setText(_translate("PaperScheduleDialog", "米數(m):", None))
        self.paperRollNumber.setText(_translate("PaperScheduleDialog", "<html><head/><body><p>顆數:</p></body></html>", None))
        self.paperScheduleTitle.setText(_translate("PaperScheduleDialog", "正規紙排單", None))
        self.paperWeight.setText(_translate("PaperScheduleDialog", "重量(kg):", None))
        self.paperWidth.setText(_translate("PaperScheduleDialog", "<html><head/><body><p>紙幅(mm):</p></body></html>", None))
        self.paperScheduleNotice.setText(_translate("PaperScheduleDialog", "請輸入排單使用量", None))
        self.paperLength_2.setText(_translate("PaperScheduleDialog", "米數(m):", None))
        self.paperWidth_2.setText(_translate("PaperScheduleDialog", "<html><head/><body><p>紙幅(mm):</p></body></html>", None))
        self.paperWeight_2.setText(_translate("PaperScheduleDialog", "重量(kg):", None))
        self.paperRollNumber_2.setText(_translate("PaperScheduleDialog", "<html><head/><body><p>顆數:</p></body></html>", None))
        self.paperScheduleNotice_2.setText(_translate("PaperScheduleDialog", "請輸入排單剩餘量", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PaperScheduleDialog = QtGui.QDialog()
    ui = Ui_PaperScheduleDialog()
    ui.setupUi(PaperScheduleDialog)
    PaperScheduleDialog.show()
    sys.exit(app.exec_())

