# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paperinput.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PaperInputDialog(object):
    def setupUi(self, PaperInputDialog):
        PaperInputDialog.setObjectName(_fromUtf8("PaperInputDialog"))
        PaperInputDialog.resize(458, 324)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PaperInputDialog.sizePolicy().hasHeightForWidth())
        PaperInputDialog.setSizePolicy(sizePolicy)
        self.paperInputButtonBox = QtGui.QDialogButtonBox(PaperInputDialog)
        self.paperInputButtonBox.setGeometry(QtCore.QRect(130, 250, 161, 32))
        self.paperInputButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.paperInputButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.paperInputButtonBox.setObjectName(_fromUtf8("paperInputButtonBox"))
        self.groupNumber = QtGui.QLabel(PaperInputDialog)
        self.groupNumber.setGeometry(QtCore.QRect(10, 52, 31, 41))
        self.groupNumber.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupNumber.setObjectName(_fromUtf8("groupNumber"))
        self.paperCustomerEdit = QtGui.QLineEdit(PaperInputDialog)
        self.paperCustomerEdit.setGeometry(QtCore.QRect(340, 90, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperCustomerEdit.sizePolicy().hasHeightForWidth())
        self.paperCustomerEdit.setSizePolicy(sizePolicy)
        self.paperCustomerEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.paperCustomerEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperCustomerEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.paperCustomerEdit.setInputMask(_fromUtf8(""))
        self.paperCustomerEdit.setText(_fromUtf8(""))
        self.paperCustomerEdit.setMaxLength(32767)
        self.paperCustomerEdit.setCursorPosition(0)
        self.paperCustomerEdit.setDragEnabled(False)
        self.paperCustomerEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperCustomerEdit.setProperty("clearButtonEnabled", False)
        self.paperCustomerEdit.setObjectName(_fromUtf8("paperCustomerEdit"))
        self.paperWeighPerUnit = QtGui.QLabel(PaperInputDialog)
        self.paperWeighPerUnit.setGeometry(QtCore.QRect(280, 50, 81, 41))
        self.paperWeighPerUnit.setObjectName(_fromUtf8("paperWeighPerUnit"))
        self.paperRollNumber = QtGui.QLabel(PaperInputDialog)
        self.paperRollNumber.setGeometry(QtCore.QRect(140, 90, 31, 31))
        self.paperRollNumber.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperRollNumber.setObjectName(_fromUtf8("paperRollNumber"))
        self.paperSpecEdit = QtGui.QLineEdit(PaperInputDialog)
        self.paperSpecEdit.setGeometry(QtCore.QRect(70, 90, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperSpecEdit.sizePolicy().hasHeightForWidth())
        self.paperSpecEdit.setSizePolicy(sizePolicy)
        self.paperSpecEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.paperSpecEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperSpecEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.paperSpecEdit.setInputMask(_fromUtf8(""))
        self.paperSpecEdit.setText(_fromUtf8(""))
        self.paperSpecEdit.setMaxLength(32767)
        self.paperSpecEdit.setCursorPosition(0)
        self.paperSpecEdit.setDragEnabled(False)
        self.paperSpecEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperSpecEdit.setProperty("clearButtonEnabled", False)
        self.paperSpecEdit.setObjectName(_fromUtf8("paperSpecEdit"))
        self.paperInputTitle = QtGui.QLabel(PaperInputDialog)
        self.paperInputTitle.setGeometry(QtCore.QRect(10, 12, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.paperInputTitle.setFont(font)
        self.paperInputTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperInputTitle.setObjectName(_fromUtf8("paperInputTitle"))
        self.paperSpec = QtGui.QLabel(PaperInputDialog)
        self.paperSpec.setGeometry(QtCore.QRect(10, 90, 51, 31))
        self.paperSpec.setObjectName(_fromUtf8("paperSpec"))
        self.paperWeighPerUnitEdit = QtGui.QLineEdit(PaperInputDialog)
        self.paperWeighPerUnitEdit.setGeometry(QtCore.QRect(350, 60, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperWeighPerUnitEdit.sizePolicy().hasHeightForWidth())
        self.paperWeighPerUnitEdit.setSizePolicy(sizePolicy)
        self.paperWeighPerUnitEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.paperWeighPerUnitEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperWeighPerUnitEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.paperWeighPerUnitEdit.setInputMask(_fromUtf8(""))
        self.paperWeighPerUnitEdit.setText(_fromUtf8(""))
        self.paperWeighPerUnitEdit.setMaxLength(32767)
        self.paperWeighPerUnitEdit.setCursorPosition(0)
        self.paperWeighPerUnitEdit.setDragEnabled(False)
        self.paperWeighPerUnitEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperWeighPerUnitEdit.setProperty("clearButtonEnabled", False)
        self.paperWeighPerUnitEdit.setObjectName(_fromUtf8("paperWeighPerUnitEdit"))
        self.paperCustomer = QtGui.QLabel(PaperInputDialog)
        self.paperCustomer.setGeometry(QtCore.QRect(280, 90, 61, 31))
        self.paperCustomer.setObjectName(_fromUtf8("paperCustomer"))
        self.groupNumberEdit = QtGui.QLineEdit(PaperInputDialog)
        self.groupNumberEdit.setGeometry(QtCore.QRect(70, 64, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupNumberEdit.sizePolicy().hasHeightForWidth())
        self.groupNumberEdit.setSizePolicy(sizePolicy)
        self.groupNumberEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.groupNumberEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.groupNumberEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.groupNumberEdit.setInputMask(_fromUtf8(""))
        self.groupNumberEdit.setText(_fromUtf8(""))
        self.groupNumberEdit.setMaxLength(32767)
        self.groupNumberEdit.setCursorPosition(0)
        self.groupNumberEdit.setDragEnabled(False)
        self.groupNumberEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.groupNumberEdit.setProperty("clearButtonEnabled", False)
        self.groupNumberEdit.setObjectName(_fromUtf8("groupNumberEdit"))
        self.paperWidthEdit = QtGui.QLineEdit(PaperInputDialog)
        self.paperWidthEdit.setGeometry(QtCore.QRect(210, 62, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperWidthEdit.sizePolicy().hasHeightForWidth())
        self.paperWidthEdit.setSizePolicy(sizePolicy)
        self.paperWidthEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.paperWidthEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperWidthEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.paperWidthEdit.setInputMask(_fromUtf8(""))
        self.paperWidthEdit.setText(_fromUtf8(""))
        self.paperWidthEdit.setMaxLength(32767)
        self.paperWidthEdit.setCursorPosition(0)
        self.paperWidthEdit.setDragEnabled(False)
        self.paperWidthEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperWidthEdit.setProperty("clearButtonEnabled", False)
        self.paperWidthEdit.setObjectName(_fromUtf8("paperWidthEdit"))
        self.paperRollNumberEdit = QtGui.QLineEdit(PaperInputDialog)
        self.paperRollNumberEdit.setGeometry(QtCore.QRect(210, 90, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paperRollNumberEdit.sizePolicy().hasHeightForWidth())
        self.paperRollNumberEdit.setSizePolicy(sizePolicy)
        self.paperRollNumberEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.paperRollNumberEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.paperRollNumberEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.paperRollNumberEdit.setInputMask(_fromUtf8(""))
        self.paperRollNumberEdit.setText(_fromUtf8(""))
        self.paperRollNumberEdit.setMaxLength(32767)
        self.paperRollNumberEdit.setCursorPosition(0)
        self.paperRollNumberEdit.setDragEnabled(False)
        self.paperRollNumberEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.paperRollNumberEdit.setProperty("clearButtonEnabled", False)
        self.paperRollNumberEdit.setObjectName(_fromUtf8("paperRollNumberEdit"))
        self.paperWidth = QtGui.QLabel(PaperInputDialog)
        self.paperWidth.setGeometry(QtCore.QRect(140, 50, 61, 41))
        self.paperWidth.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paperWidth.setObjectName(_fromUtf8("paperWidth"))
        self.groupNumber.raise_()
        self.paperCustomerEdit.raise_()
        self.paperWeighPerUnit.raise_()
        self.paperRollNumber.raise_()
        self.paperSpecEdit.raise_()
        self.paperInputTitle.raise_()
        self.paperSpec.raise_()
        self.paperWeighPerUnitEdit.raise_()
        self.paperCustomer.raise_()
        self.groupNumberEdit.raise_()
        self.paperWidthEdit.raise_()
        self.paperRollNumberEdit.raise_()
        self.paperWidth.raise_()
        self.paperInputButtonBox.raise_()

        self.retranslateUi(PaperInputDialog)
        QtCore.QObject.connect(self.paperInputButtonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PaperInputDialog.accept)
        QtCore.QObject.connect(self.paperInputButtonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PaperInputDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PaperInputDialog)
        PaperInputDialog.setTabOrder(self.groupNumberEdit, self.paperSpecEdit)
        PaperInputDialog.setTabOrder(self.paperSpecEdit, self.paperWidthEdit)
        PaperInputDialog.setTabOrder(self.paperWidthEdit, self.paperRollNumberEdit)
        PaperInputDialog.setTabOrder(self.paperRollNumberEdit, self.paperWeighPerUnitEdit)
        PaperInputDialog.setTabOrder(self.paperWeighPerUnitEdit, self.paperCustomerEdit)
        PaperInputDialog.setTabOrder(self.paperCustomerEdit, self.paperInputButtonBox)

    def retranslateUi(self, PaperInputDialog):
        PaperInputDialog.setWindowTitle(_translate("PaperInputDialog", "正規紙輸入", None))
        self.groupNumber.setText(_translate("PaperInputDialog", "<html><head/><body><p>批號:</p></body></html>", None))
        self.paperWeighPerUnit.setText(_translate("PaperInputDialog", "原基重(gsm):", None))
        self.paperRollNumber.setText(_translate("PaperInputDialog", "<html><head/><body><p>顆數:</p></body></html>", None))
        self.paperInputTitle.setText(_translate("PaperInputDialog", "<html><head/><body><p>正規紙輸入</p></body></html>", None))
        self.paperSpec.setText(_translate("PaperInputDialog", "基重條數:", None))
        self.paperCustomer.setText(_translate("PaperInputDialog", "客戶:", None))
        self.paperWidth.setText(_translate("PaperInputDialog", "<html><head/><body><p>紙幅(mm):</p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PaperInputDialog = QtGui.QDialog()
    ui = Ui_PaperInputDialog()
    ui.setupUi(PaperInputDialog)
    PaperInputDialog.show()
    sys.exit(app.exec_())

